before_install:
  - rvm install jruby-1.7.15
  - rvm use jruby-1.7.15@uc6clientapi --create

install:
  - bundle install

before_script:
  - echo "Skipping DB setup"

script:
  - bundle exec rspec spec
